### PR TITLE
Fix homepage code

### LINKED ISSUE #34: Refactor and fix homepage code
There are some duplicate code and unused commented lines, in-lined styles in the homepage code. Needs refactoring before it gets messy.

### PR DESCRIPTION
**Pull request by olcayakman**
fixed homepage code and added new navigation item to later add info about the product to the website (the dropdown nav item)

### CODE REVIEW

File: web/src/views/HomepageView.jsx [hunk 1]
```diff
@@ -1,54 +1,69 @@
...
+        //                 e-commerce website that integrates the API and helps both the
+        //                 retailer and their customer. Kalas-Iris can be integrated to any e-
+        //                 commerce website and it provides a very simple API. The annotation
+        //                 and search process is automized with our solution to provide the
+        //                 customers with the possible best experience.
+        //                 </h2>
+        //             </header>
+        //         </div>
+        //     </Row>
+        // </>
```
Comment (AtaAtasoy) [inline web/src/views/HomepageView.jsx]: Why is this block commented out ? For future use ? What are your plans for it ?

File: web/src/views/HomepageView.jsx [hunk 2]
```diff
@@ -1,54 +1,69 @@
 import React, { useState } from "react";
-import { Carousel } from "antd";
+import { Carousel, Row, Column } from "antd";
 import { Divider, Image } from "antd";
 
 const contentStyle = {
```
Comment (AtaAtasoy) [inline web/src/views/HomepageView.jsx:8]: I've read that, it's not a good approach to include inline CSS in the jsx file. Can you move them to another CSS file ?  You can refer to [here](https://www.sitepoint.com/react-components-styling-options/) for React component styling options.

File: web/src/App.js [hunk 3]
```diff
@@ -49,9 +48,6 @@ function App() {
   }, []);
 
   const menuBarStyle = {
```
Comment (AtaAtasoy) [inline web/src/App.js:54]: Inline styling is not recommended as discussed above.

File: web/src/App.js [hunk 4]
```diff
@@ -18,7 +18,6 @@ function App() {
   const location = useLocation();
 
   const menuLinks = [
```
Comment (AtaAtasoy) [inline web/src/App.js:24]: Inline styling again

**Review by AtaAtasoy — CHANGES_REQUESTED** [review]
Its not recommended to have inline styling attributes in React. It would be better to use another approach. I have linked a document for you to check it out. Other than that the code seems fine

File: web/src/App.js [hunk 5]
```diff
@@ -49,16 +51,28 @@ function App() {
...
-    // backgroundColor: "#f7c873",
-    //color: "#bd8e02",
     color: '#434343',
     textColor: '#434343',
     backgroundColor: "#001529"
   };
 
   const [isShown, setIsShown] = useState(false);
 
+  const dropdown1 = (
```
Comment (AtaAtasoy) [inline web/src/App.js:62]: I think it would be better to define this component outside App.js and import it here. What do you think @Dogacel  ?

File: web/src/views/FashionAnnotationInfoView.jsx [hunk 6]
```diff
@@ -0,0 +1,16 @@
+import React from "react";
+
+export default function FashionAnnotationInfoView() {
+    const onFinish = values => {
```
Comment (AtaAtasoy) [inline web/src/views/FashionAnnotationInfoView.jsx]: I don't think this component needs an onFinish hook.

**Review by AtaAtasoy — CHANGES_REQUESTED** [review]

File: web/src/App.js (hunk 3 above)
Comment (AtaAtasoy) [reply web/src/App.js:54]: The code was updated quickly thus I'm not sure if you had the chance to look into my comments, thus I'm writing the issue about inline styling here and resolving other conversations  regarding inline styling. 

I've read that, it's not a good approach to include inline styling in the jsx file. Can you move them to another CSS file ?  You can refer to [here](https://www.sitepoint.com/react-components-styling-options/) for React component styling options.

File: web/src/views/HomepageView.jsx (hunk 1 above)
Comment (AtaAtasoy) [reply web/src/views/HomepageView.jsx]: This code was updated, thus resolving the conversation.

**Review by AtaAtasoy — CHANGES_REQUESTED** [review]
* I don't think the FashionAnnotationView component does not need a onFinish hook atm. 
* You should also take another approach to styling your components, different from inline styling.

File: web/src/views/FashionAnnotationInfoView.jsx (hunk 6 above)
Comment (olcayakman) [reply web/src/views/FashionAnnotationInfoView.jsx]: I agree i will remove it

File: web/src/views/HomepageView.jsx [hunk 7]
```diff
@@ -20,17 +20,15 @@ export default function HomepageView() {
...
                     src={process.env.PUBLIC_URL + '/carousel-1-image.jpeg'}
                     preview={false}
                 />
             </div>
 
             <div>
                 <Image 
-                    width={1200}
-                    height={675}
+                    style={contentStyle}
```
Comment (AtaAtasoy) [inline web/src/views/HomepageView.jsx:36]: Okay, one last thing 😄 I see that you removed the inline styling, is it possible that you forgot to push the updated CSS file ? I can't see where contentStyle is defined in this commit.

**Review by AtaAtasoy — DISMISSED** [review]

File: web/src/App.js (hunk 5 above)
Comment (Dogacel) [reply web/src/App.js:62]: Yes, this file gets bigger and bigger. It is not necessary right now but if we are going to add more to the header, we should move the header component outside and just leave routes/structure logic inside App.js.

File: web/src/views/HomepageView.jsx (hunk 7 above)
Comment (AtaAtasoy) [reply web/src/views/HomepageView.jsx:36]: Ok, it must have slipped by me. contentStyle is defined in the HomepageView.jsx file

**Review by zeynepkorkunc — APPROVED** [review]
